/*******************************************************************************
* File Name: cyfitter_gpio.h
* 
* PSoC Creator  4.4
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_GPIO_H
#define INCLUDED_CYFITTER_GPIO_H
#include "cy_device_headers.h"

/* LED_OK */
#define LED_OK_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LED_OK_0_INBUF_ENABLED 0u
#define LED_OK_0_INIT_DRIVESTATE 1u
#define LED_OK_0_INIT_MUXSEL 0u
#define LED_OK_0_INPUT_SYNC 2u
#define LED_OK_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LED_OK_0_NUM 1u
#define LED_OK_0_PORT GPIO_PRT1
#define LED_OK_0_SLEWRATE CY_GPIO_SLEW_FAST
#define LED_OK_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define LED_OK_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LED_OK_INBUF_ENABLED 0u
#define LED_OK_INIT_DRIVESTATE 1u
#define LED_OK_INIT_MUXSEL 0u
#define LED_OK_INPUT_SYNC 2u
#define LED_OK_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LED_OK_NUM 1u
#define LED_OK_PORT GPIO_PRT1
#define LED_OK_SLEWRATE CY_GPIO_SLEW_FAST
#define LED_OK_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* LED_ERROR */
#define LED_ERROR_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LED_ERROR_0_INBUF_ENABLED 0u
#define LED_ERROR_0_INIT_DRIVESTATE 1u
#define LED_ERROR_0_INIT_MUXSEL 0u
#define LED_ERROR_0_INPUT_SYNC 2u
#define LED_ERROR_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LED_ERROR_0_NUM 3u
#define LED_ERROR_0_PORT GPIO_PRT0
#define LED_ERROR_0_SLEWRATE CY_GPIO_SLEW_FAST
#define LED_ERROR_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define LED_ERROR_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LED_ERROR_INBUF_ENABLED 0u
#define LED_ERROR_INIT_DRIVESTATE 1u
#define LED_ERROR_INIT_MUXSEL 0u
#define LED_ERROR_INPUT_SYNC 2u
#define LED_ERROR_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LED_ERROR_NUM 3u
#define LED_ERROR_PORT GPIO_PRT0
#define LED_ERROR_SLEWRATE CY_GPIO_SLEW_FAST
#define LED_ERROR_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* UART_1_rx */
#define UART_1_rx_0_DRIVEMODE CY_GPIO_DM_HIGHZ
#define UART_1_rx_0_INBUF_ENABLED 1u
#define UART_1_rx_0_INIT_DRIVESTATE 1u
#define UART_1_rx_0_INIT_MUXSEL 18u
#define UART_1_rx_0_INPUT_SYNC 2u
#define UART_1_rx_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_1_rx_0_NUM 0u
#define UART_1_rx_0_PORT GPIO_PRT5
#define UART_1_rx_0_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_1_rx_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define UART_1_rx_DRIVEMODE CY_GPIO_DM_HIGHZ
#define UART_1_rx_INBUF_ENABLED 1u
#define UART_1_rx_INIT_DRIVESTATE 1u
#define UART_1_rx_INIT_MUXSEL 18u
#define UART_1_rx_INPUT_SYNC 2u
#define UART_1_rx_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_1_rx_NUM 0u
#define UART_1_rx_PORT GPIO_PRT5
#define UART_1_rx_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_1_rx_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* UART_1_tx */
#define UART_1_tx_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define UART_1_tx_0_INBUF_ENABLED 0u
#define UART_1_tx_0_INIT_DRIVESTATE 1u
#define UART_1_tx_0_INIT_MUXSEL 18u
#define UART_1_tx_0_INPUT_SYNC 2u
#define UART_1_tx_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_1_tx_0_NUM 1u
#define UART_1_tx_0_PORT GPIO_PRT5
#define UART_1_tx_0_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_1_tx_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define UART_1_tx_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define UART_1_tx_INBUF_ENABLED 0u
#define UART_1_tx_INIT_DRIVESTATE 1u
#define UART_1_tx_INIT_MUXSEL 18u
#define UART_1_tx_INPUT_SYNC 2u
#define UART_1_tx_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_1_tx_NUM 1u
#define UART_1_tx_PORT GPIO_PRT5
#define UART_1_tx_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_1_tx_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

#endif /* INCLUDED_CYFITTER_GPIO_H */
