/*
 * LED.h
 *
 *  Created on: 09-Oct-2021
 *      Author: AustinA
 */

#ifndef SOURCE_HAL_LED_H_
#define SOURCE_HAL_LED_H_

#include "common.h"

#ifndef _RGB_GPIO_SCRATCH_MODE_DISABLE

#define CYBSP_LED_RGB_RED_PORT 			GPIO_PRT0
#define CYBSP_LED_RGB_RED_PORT_NUM		CYBSP_LED_RGB_RED_PORT
#define CYBSP_LED_RGB_RED_PIN 			3U
#define CYBSP_LED_RGB_RED_HSIOM 		HSIOM_SEL_GPIO

#define CYBSP_LED_RGB_GREEN_PORT 		GPIO_PRT1
#define CYBSP_LED_RGB_GREEN_PORT_NUM	CYBSP_LED_RGB_GREEN_PORT
#define CYBSP_LED_RGB_GREEN_PIN 		1U
#define CYBSP_LED_RGB_GREEN_HSIOM 		HSIOM_SEL_GPIO

#define CYBSP_LED_RGB_BLUE_PORT 		GPIO_PRT11
#define CYBSP_LED_RGB_BLUE_PORT_NUM		CYBSP_LED_RGB_BLUE_PORT
#define CYBSP_LED_RGB_BLUE_PIN 			1U
#define CYBSP_LED_RGB_BLUE_HSIOM 		HSIOM_SEL_GPIO

#endif

#define CYBSP_LED9_PORT 				GPIO_PRT13
#define CYBSP_LED9_PORT_NUM				CYBSP_LED9_PORT
#define CYBSP_LED9_PIN 					7U
#define CYBSP_LED9_HSIOM 				HSIOM_SEL_GPIO

#define CYBSP_LED8_PORT 				GPIO_PRT1
#define CYBSP_LED8_PORT_NUM				CYBSP_LED8_PORT
#define CYBSP_LED8_PIN 					5U
#define CYBSP_LED8_HSIOM 				HSIOM_SEL_GPIO


void LEDsInit();


#endif /* SOURCE_HAL_LED_H_ */
